version: '3'
services:
    nginx:
        restart: always
        image: nginx
        container_name: nginx
        expose:
            - 80
        ports:
            - 8091:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./vuepress/:/var/www/html/
            - ./vuepress/images:/images
