version: '3'
services:
    nginx:
        restart: always
        image: nginx
        container_name: nginx
        ports:
            - 6001:443
            - 6002:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/logs/:/etc/nginx/logs
            - ./nginx/cert:/etc/nginx/cert
            - ./dist:/var/www/html
            - ./yaml:/var/www/html/vps
#             - ./dist/images:/static
#             - /etc/v2ray/:/etc/v2ray
#             - /var/log/nginx/:/var/log/nginx
#             - /usr/share/nginx/:/usr/share/nginx
#             - /root/yh/nginx/:/root/yh/nginx
