version: '3'
services:
    nginx:
        restart: always
        image: nginx
        container_name: nginx
        ports:
            - 3389:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./dist:/var/www/html
            - ./dist/images:/static
