version: '3'
services:
    nginx:
        restart: always
        image: nginx
        container_name: nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/logs/:/etc/nginx/logs
            - ./nginx/cert:/etc/nginx/cert
            - ./dist:/var/www/html
            - ./yaml:/static
            - ./dist/images:/static
