version: '3.1'
services: 
    nginx:
        restart: always
        image: nginx
        container_name: nginx
        ports: 
            - 8091:80
        volumes:
            - ./nginx/conf:/etc/nginx/conf
            - ./dist:/var/www/dist
            - ./images:/images
