version: '3.1'
services: 
    nginx:
        restart: always
        image: nginx
        ports: 
            - 8091:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d /
            - ./dist/:/var/www/html/
            - ./images/:/images/
